### ISSUE TITLE
Visually highlight a node when hovering/clicking

### ISSUE THREAD

**Issue by Stukova** [cosmograph-org/cosmos#24]
Presumably with a ring around the hovered/clicked node.

**Comment by thorwhalen** [comment]
I'd vote yes, but personally I'd say
* on hover
* the capability of turning that off (in some contexts it may be undesirable)
The question here is: Is it on by default. Off the top of my head I'd say yes. 

I say "on hover", but perhaps we can also allow "on click", or both. 

I say perhaps because I'm thinking that perhaps we want to keep the click for something that's very useful for a data analyst: **Selection** (and "... with selection; actions"). 

That's the matter of a different issue though.

**Comment by Stukova** [comment]
Added `renderHighlightedNodeRing` and `highlightedNodeRingColor` configuration properties in [`1.3.0`](https://github.com/cosmograph-org/cosmos/releases/tag/1.3.0)
